backend_app/urls.py
from django.urls import path
from backend_app import views
from backend_app.apps import BackendAppConfig

app_name = BackendAppConfig.name

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('products/', views.products, name='products'),
    path('show_cart/', views.show_cart, name='show_cart'),
    path('forgot_password/', views.ForgotPassword.as_view(), name='forgot_password'),
    path('update_password/', views.UpdatePassword.as_view(), name='update_password'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('change_password/', views.ChangePassword.as_view(), name='change_password'),
    path('update_my_profile/', views.update_my_profile, name='update_my_profile'),
    path('add_product/', views.AddProduct.as_view(), name='add_product'),
    path('login/', views.MyLogin.as_view(), name='login'),
    path('register/', views.AdminRegistration.as_view(), name='admin_registration'),
    path('admin_index/', views.admin_index, name='admin_index'),
    path('view_products/', views.view_products, name='view_products'),
    path('add_category/', views.add_category, name='add_category'),
    path('view_categories/', views.view_categories, name='view_categories'),
    path('update_category/<int:pk>/', views.update_category, name='update_category'),
    path('qty_increase_decrease/', views.qty_increase_decrease, name='qty_increase_decrease'),
    path('checkout_page/', views.checkout_page, name='checkout_page'),
    path('delete_cart_item/<int:pk>/', views.delete_cart_item, name='delete_cart_item'),
    path('delete_category/<int:pk>/', views.delete_category, name='delete_category'),
    path('delete_product/<int:pk>/', views.delete_product, name='delete_product'),
]

creative_spaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from backend_app import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend_app.urls', namespace='backend')),
    path('professional/', include('professionals.urls', namespace='professionals')),
    path('user/', include('users.urls', namespace='users')),
    path('verify/', views.user_verification, name='verify'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('forgot_password_verify/', views.forgot_password_verification, name='forgot_password_verification'),
    path('logout/', views.my_logout, name="logout"),
    path('payment_processing/', views.payment_processing, name='payment_processing'),
    path('payment_successful/', views.payment_successful, name='payment_successful'),
    path('payment_failed/', TemplateView.as_view(template_name='payment_failed'), name='payment_failed'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", views.UserRegistration.as_view(), name="user_register"),
    path('index/', views.user_index, name='user_index'),
    path('ask_a_question/', views.ask_a_question, name='ask_a_question'),
    path('question/', views.question, name='question'),
    path('answer_questions/', views.answer_questions, name='answer_questions'),
    path('add_review/', views.add_review, name='add_review'),
    path('view_profile/', views.view_profile, name='view_profile'),
]

templates/about_us.html
{% extends 'master.html' %}

{% block title %}
Creative Spaces|About Us
{% endblock %}

{% block content %}
<!-- banner -->
	<div class="banner-w3ls-2">

	</div>
	<!-- //banner -->
	<!-- page details -->
	<div class="breadcrumb-agile">
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="/">Home</a>
			</li>
			<li class="breadcrumb-item active" aria-current="page">About Us</li>
		</ol>
	</div>
	<!-- //page details -->

	<!-- about section -->
	<div class="inner-sec-w3ls py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="row">
				<div class="col-lg-6 about-img">
					<img class="img-fluid" src="../static/images/main.jpg" alt="">
				</div>
				<div class="col-lg-6 about-right mt-xl-5 mt-lg-3 mt-sm-5 mt-4 pt-lg-2">
					<h2 class="sub-tittle text-uppercase font-weight-bold">About Us</h2>
					<h1 class="tittle mt-2">We Do Great Design For Creative Folks.</h1>
					<p class="mt-4">Lorem ipsum dolor sit amet Neque porro quisquam est qui dolorem Lorem int ipsum dolor sit amet
						when an unknown printer took a galley of type.Vivamus id tempor felis. Cras sagittis mi sit amet malesuada
						mollis. Mauris porroinit consectetur cursus tortor vel interdum.</p>
					<a href="blog.html" class="btn button-style mt-sm-5 mt-4">Read More</a>
				</div>
			</div>
		</div>
	</div>
	<!-- //about section -->

	<!-- brands -->
	<div class="bottom-w3pvt pb-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-sm-5 mb-4 text-dark text-center font-weight-bold">Our Brands</h3>
			<ul class="list-unstyled brands text-center pt-5">
				<li><i class="fa fa-gg" aria-hidden="true"></i></li>
				<li><i class="fa fa-houzz active" aria-hidden="true"></i></li>
				<li><i class="fa fa-yoast" aria-hidden="true"></i></li>
				<li><i class="fa fa-skyatlas" aria-hidden="true"></i></li>
				<li><i class="fa fa-pied-piper active" aria-hidden="true"></i></li>
			</ul>
		</div>
	</div>
	<!-- //brands -->

	<!-- about bottom -->
	<div class="blog-w3ls py-5 bg-light border-bottom" id="what">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-sm-5 mb-4 text-dark text-center font-weight-bold">What we do</h3>
			<p class="title-para text-center mx-auto mb-sm-5 mb-4">Ut enim ad minim veniam, quis nostrud exercitation ullamco
				laboris nisi ut aliquip ex ea commodo consequat, dolor sit amet consectetur elit.</p>
			<div class="row package-grids">
				<div class="col-md-4 blog-w3">
					<div class="blogs-top">
						<img src="../static/images/w1.jpg" alt="" class="img-fluid" />
					</div>
					<div class="blogs-bottom p-4 bg-white">
						<h4 class="text-dark font-weight-bold mb-3">Architecture</h4>
						<a href="about.html">
							<i class="fa fa-line-chart mr-2"></i>Learn More</a>
					</div>
				</div>
				<div class="col-md-4 blog-w3 my-md-0 my-5">
					<div class="blogs-top">
						<img src="../static/images/w2.jpg" alt="" class="img-fluid" />
					</div>
					<div class="blogs-bottom p-4 bg-white">
						<h4 class="text-dark font-weight-bold mb-3">Interior Design</h4>
						<a href="about.html">
							<i class="fa fa-paint-brush mr-2"></i>Learn More</a>
					</div>
				</div>
				<div class="col-md-4 blog-w3">
					<div class="blogs-top">
						<img src="../static/images/w3.jpg" alt="" class="img-fluid" />
					</div>
					<div class="blogs-bottom p-4 bg-white">
						<h4 class="text-dark font-weight-bold mb-3">Engineering</h4>
						<a href="about.html">
							<i class="fa fa-gavel mr-2"></i>Learn More</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //about bottom -->

	<!-- services -->
	<section class="banner-bottom-w3layouts py-5" id="services">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-sm-5 mb-4 text-dark text-center font-weight-bold">Our Services</h3>
			<p class="title-para text-center mx-auto mb-sm-5 mb-4">Ut enim ad minim veniam, quis nostrud exercitation ullamco
				laboris nisi ut aliquip ex ea commodo consequat, dolor sit amet consectetur elit.</p>
			<div class="row pt-sm-4">
				<div class="col-lg-4 about-in text-center">
					<div class="card">
						<div class="card-body">
							<i class="fa fa-gavel mb-4" aria-hidden="true"></i>
							<h5 class="card-title mb-3">Heading Here</h5>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur elit,Adipisicing elit tempor.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 about-in text-center my-lg-0 my-4">
					<div class="card active">
						<div class="card-body">
							<i class="fa fa-paint-brush mb-4" aria-hidden="true"></i>
							<h5 class="card-title mb-3">Heading Here</h5>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur elit,Adipisicing elit tempor.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 about-in text-center">
					<div class="card">
						<div class="card-body">
							<i class="fa fa-magic mb-4" aria-hidden="true"></i>
							<h5 class="card-title mb-3">Heading Here</h5>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur elit,Adipisicing elit tempor.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row mt-lg-4">
				<div class="col-lg-4 about-in mt-lg-4 text-center">
					<div class="card">
						<div class="card-body">
							<i class="fa fa-wrench mb-4" aria-hidden="true"></i>
							<h5 class="card-title mb-3">Heading Here</h5>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur elit,Adipisicing elit tempor.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 about-in mt-lg-4 text-center">
					<div class="card">
						<div class="card-body">
							<i class="fa fa-cogs mb-4" aria-hidden="true"></i>
							<h5 class="card-title mb-3">Heading Here</h5>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur elit,Adipisicing elit tempor.</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4 about-in mt-lg-4 text-center">
					<div class="card">
						<div class="card-body">
							<i class="fa fa-line-chart mb-4" aria-hidden="true"></i>
							<h5 class="card-title mb-3">Heading Here</h5>
							<p class="card-text">Lorem ipsum dolor sit amet consectetur elit,Adipisicing elit tempor.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- //services -->

	<!-- team -->
	<div class="team bg-light py-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-sm-5 mb-4 text-dark text-center font-weight-bold">Our Team Members</h3>
			<p class="title-para text-center mx-auto mb-sm-5 mb-4">Ut enim ad minim veniam, quis nostrud exercitation ullamco
				laboris nisi ut aliquip ex ea commodo consequat, dolor sit amet consectetur elit.</p>
			<div class="row mt-30">
				<div class="col-lg-4">
					<div class="box16">
						<img src="../static/images/team1.jpg" alt="" class="img-fluid">
						<div class="box-content">
							<h3 class="title">Petey Cruiser</h3>
							<span class="post">Designer</span>
							<ul class="social">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-4 my-lg-0 my-5">
					<div class="box16">
						<img src="../static/images/team2.jpg" alt="" class="img-fluid">
						<div class="box-content">
							<h3 class="title">Sal Monella</h3>
							<span class="post">Designer</span>
							<ul class="social">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="box16">
						<img src="../static/images/team3.jpg" alt="" class="img-fluid">
						<div class="box-content">
							<h3 class="title">Matt Innae</h3>
							<span class="post">Designer</span>
							<ul class="social">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //team -->

	<!-- ways -->
	<div class="join-w3l1 py-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 title-w3-3 mb-sm-5 mb-4 text-dark text-center font-weight-bold">We Do Great Design For Creative
				Folks.</h3>
			<div class="row join-agile2 text-center pt-md-5 pt-4">
				<div class="col-md-3 steps-reach-w3l">
					<span class="fa fa-check-square-o" aria-hidden="true"></span>
					<p class="mt-3">Dream Design</p>
					<div class="style-agile-border">
						<img src="../static/images/sty1.png" alt="" />
					</div>
				</div>
				<div class="col-md-3 steps-reach-w3l my-md-0 my-4">
					<span class="fa fa-volume-control-phone" aria-hidden="true"></span>
					<p class="mt-3">Contact Us</p>
					<div class="style-agile-border second-border">
						<img src="../static/images/sty2.png" alt="" />
					</div>
				</div>
				<div class="col-md-3 steps-reach-w3l">
					<span class="fa fa-calendar" aria-hidden="true"></span>
					<p class="mt-3">Choose the Date</p>
					<div class="style-agile-border">
						<img src="../static/images/sty1.png" alt="" />
					</div>
				</div>
				<div class="col-md-3 steps-reach-w3l mt-md-0 mt-4">
					<span class="fa fa-smile-o" aria-hidden="true"></span>
					<p class="mt-3">Design Ready</p>
				</div>
			</div>
		</div>
	</div>
	<!-- //ways -->

	<!-- testimonials -->
	<div class="testimonials text-center py-5" id="testi">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-5 text-white text-center font-weight-bold">Testimonials</h3>
			<div id="carouselExampleIndicators" class="carousel slide pb-5" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
					<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
					<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
				</ol>
				<div class="carousel-inner">
					<div class="carousel-item active">
						<div class="w3_testimonials_grid">
							<img src="../static/images/te1.jpg" alt=" " class="img-fluid rounded-circle" />
							<h5 class="mt-3 text-white">Thomas Carl - Sed do eiusmod</h5>
							<h4 class="mx-auto mt-4 text-light">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
								quo minus
								id quod possimus,
								omnis voluptas.
							</h4>
						</div>
					</div>
					<div class="carousel-item">
						<div class="w3_testimonials_grid">
							<img src="../static/images/te2.jpg" alt=" " class="img-fluid rounded-circle" />
							<h5 class="mt-3 text-white">Petey Cruiser - Sed do eiusmod</h5>
							<h4 class="mx-auto mt-4 text-light">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
								quo minus
								id quod possimus,
								omnis voluptas.
							</h4>
						</div>
					</div>
					<div class="carousel-item">
						<div class="w3_testimonials_grid">
							<img src="../static/images/te3.jpg" alt=" " class="img-fluid rounded-circle" />
							<h5 class="mt-3 text-white">Speed Wagon - Sed do eiusmod</h5>
							<h4 class="mx-auto mt-4 text-light">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
								quo minus
								id quod possimus,
								omnis voluptas.
							</h4>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- //testimonials -->
{% endblock %}

templates/login.html
{% extends 'master.html' %}


{% block title %}
Creative Spaces | Login
{% endblock %}


{% block content %}

<div class="contact py-5">
		<div class="container py-xl-5 py-lg-3">
			<h3 class="title-w3 mb-sm-5 mb-4 text-dark text-center font-weight-bold">Login</h3>
			<div class="row contact-form">
				<div class="col-lg-12">
					<!-- contact form -->
					<div class="contact-top1">
						<form method="post" class="contact-wthree">
								<div class="form-group d-flex mx-auto w-50 mt-1">
									<label>
										<i class="fa fa-user" aria-hidden="true"></i>
									</label>
									<input class="form-control" type="email" placeholder="Enter your email" name="email" required="">
								</div>

								<div class="form-group d-flex mx-auto w-50 mt-4">
									<label>
										<i class="fa fa-lock" aria-hidden="true"></i>
									</label>
									<input class="form-control" type="password" placeholder="Enter your password" name="password" required="">
								</div>

								<div class="form-group d-flex mx-auto w-50 mt-4">
									<a href="/forgot_password/" class="text-dark">Forgot password?</a>
								</div>
							<div class="d-flex justify-content-center mt-4">
								<button type="submit" class="btn text-white btn-block w-25">Submit</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% if email_invalid %}
<div class="alert alert-danger alert-dismissible">
	<a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<strong>Invalid Email! </strong>
	Please enter correct one.
</div>
{% elif password_invalid %}
<div class="alert alert-danger alert-dismissible">
	<a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<strong>Invalid Password!</strong>
	Please enter correct one.
</div>
{% elif not_verify %}
<div class="alert alert-danger alert-dismissible">
	<a href="" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	<strong>Please verify your email first!</strong>
	Only then you'll be allowed to log in.
</div>
{% endif %}


{% endblock %}

templates/master.html
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>
		{% block title %}{% endblock %}
	</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Inside Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="/static/css/bootstrap.css">
	<!-- Bootstrap-Core-CSS -->
	<link rel="stylesheet" href="/static/css/style.css" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link rel="stylesheet" href="/static/css/font-awesome.css">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i&amp;subset=latin-ext"
	 rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	 rel="stylesheet">
	<!-- //Web-Fonts -->
</head>

<body>
	<!-- header -->
	<header>
		<!-- navigation -->
		<div class="main-top py-1">
			<nav class="navbar navbar-expand-lg navbar-light fixed-navi">
				<div class="container-fluid">
					<!-- logo -->
					<a class="navbar-brand font-weight-bold" href="{% url 'backend:index' %}">
						<i class="fa fa-ils mr-2" aria-hidden="true"></i>Creative Spaces
					</a>
					<!-- //logo -->
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
						<ul class="navbar-nav ml-lg-auto">
							<li class="nav-item active">
								<a class="nav-link" href="{% url 'backend:index' %}">Home
									<span class="sr-only">(current)</span>
								</a>
							</li>
							<li class="nav-item mx-xl-5 mx-lg-3 my-lg-0 my-3">
								<a class="nav-link" href="{% url 'backend:products' %}">Products</a>
							</li>


							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
								 aria-haspopup="true" aria-expanded="false">
									Register
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown">
									<a class="dropdown-item" href="/user/register/">User</a>
									{% if not request.session.admin_exists %}
									<a class="dropdown-item" href="{% url 'backend:admin_registration' %}">Admin</a>
									{% endif %}
									<a class="dropdown-item" href="/professional/registration/">Professional</a>
								</div>
							</li>


							<li class="nav-item mx-xl-5 mx-lg-3 mt-lg-0 mt-3">
								<a class="nav-link" href="{% url 'backend:portfolio' %}">Portfolio</a>
							</li>

							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown"
								 aria-haspopup="true" aria-expanded="false">
									More
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
									<a class="dropdown-item" href="{% url 'backend:about_us' %}">About Us</a>
									<a class="dropdown-item" href="{% url 'users:ask_a_question' %}">Professionals</a>
								</div>
							</li>
							<!--<li class="nav-item mt-lg-0 mt-3">
								<a class="nav-link" href="">Contact Us</a>
							</li>-->
							<li class="search my-lg-0 my-4">
								{% if request.session.role != 'professional' and request.session.role != 'admin' %}
								<a href="/show_cart/">
									<i class="fa fa-shopping-cart" aria-hidden="true"></i>
								</a>
								{% endif %}
<!--								<div id="small-dialog" class="mfp-hide">-->
<!--									<div class="search-top">-->
<!--										<div class="search-inn">-->
<!--											<form action="#" method="post" class="disply-flex">-->
<!--												<input class="form-control" type="search" name="search" placeholder="Type something..." required>-->
<!--												<button class="btn2">-->
<!--													<i class="fa fa-shopping-cart" aria-hidden="true"></i>-->
<!--												</button>-->
<!--											</form>-->
<!--											<p class="text-white font-weight-bold mt-4">Creative Spaces</p>-->
<!--										</div>-->
<!--									</div>-->
<!--								</div>-->
							</li>
							<li class="ml-lg-4 mb-lg-0 mb-4">
								{% if not request.session.logged_in %}
								<a href="{% url 'backend:login' %}" class="reqe-button">Login</a>
								{% else %}
								<a href="{% url 'backend:login' %}" class="reqe-button">Dashboard</a>
								{% endif %}
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>
		<!-- //navigation -->
	</header>
	<!-- //header -->

	{% block content %} {% endblock %}

<!-- footer -->
	<footer>
		<div class="w3ls-footer-grids py-4">
			<div class="container py-xl-5 py-lg-3">
				<div class="row">
					<div class="col-lg-3 w3l-footer-logo text-center">
						<!-- logo -->
						<a class="navbar-brand font-weight-bold" href="index.html">
							<i class="fa fa-ils mr-2" aria-hidden="true"></i>Creative Spaces
						</a>
						<!-- //logo -->
					</div>
					<!-- button -->
					<div class="col-lg-5 w3l-footer text-lg-right text-center mt-3">
						<ul class="list-unstyled footer-nav-wthree">
							<li class="mr-4">
								<a href="index.html" class="active">Home</a>
							</li>
							<li class="mr-4">
								<a class="" href="about.html">About Us</a>
							</li>
							<li class="mr-4">
								<a class="" href="gallery.html">Gallery</a>
							</li>
							<li>
								<a class="" href="contact.html">Contact Us</a>
							</li>
						</ul>
					</div>
					<!-- //button -->
					<!-- social icons -->
					<div class="col-lg-4 w3social-icons text-lg-right text-center mt-lg-0 mt-3">
						<ul>
							<li>
								<a href="#" class="rounded-circle">
									<i class="fa fa-facebook-f"></i>
								</a>
							</li>
							<li class="px-2">
								<a href="#" class="rounded-circle">
									<i class="fa fa-google-plus"></i>
								</a>
							</li>
							<li>
								<a href="#" class="rounded-circle">
									<i class="fa fa-twitter"></i>
								</a>
							</li>
						</ul>
					</div>
					<!-- //social icons -->
				</div>

			</div>
		</div>
	</footer>
	<!-- //footer -->

	<!-- Js files -->
	<!-- JavaScript -->
	<script src="/static/js/jquery-2.2.3.min.js"></script>
	<!-- Default-JavaScript-File -->
	<script src="/static/js/bootstrap.js"></script>
	<!-- Necessary-JavaScript-File-For-Bootstrap -->

	<!-- fixed navigation -->
	<script src="/static/js/fixed-nav.js"></script>
	<!-- //fixed navigation -->
	<!-- dropdown smooth -->
	<script>
		$(document).ready(function () {
				$(".dropdown").hover(
					function () {
						$('.dropdown-menu', this).stop(false, false).slideDown("fast");
						$(this).toggleClass('open');
					},
					function () {
						$('.dropdown-menu', this).stop(true, true).slideUp("fast");
						$(this).toggleClass('open');
					}
				);
			});
		</script>
	<!-- //dropdown smooth -->

	<!-- search plugin -->
	<!-- pop-up-box -->
	<link href="/static/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />
	<script src="/static/js/jquery.magnific-popup.js"></script>
	<!-- //pop-up-box -->
	<!-- search script -->
	<script>
		$(document).ready(function () {
			$('.popup-with-zoom-anim').magnificPopup({
				type: 'inline',
				fixedContentPos: false,
				fixedBgPos: true,
				overflowY: 'auto',
				closeBtnInside: true,
				preloader: false,
				midClick: true,
				removalDelay: 300,
				mainClass: 'my-mfp-zoom-in'
			});

		});
	</script>
	<!-- //search script -->
	<!-- //search plugin -->

	<!-- smooth scrolling -->
	<script src="/static/js/SmoothScroll.min.js"></script>
	<!-- move-top -->
	<script src="/static/js/move-top.js"></script>
	<!-- easing -->
	<script src="/static/js/easing.js"></script>
	<!--  necessary snippets for few javascript files -->
	<script src="/static/js/inside.js"></script>

	<script src="/static/js/bootstrap.js"></script>
	<!-- Necessary-JavaScript-File-For-Bootstrap -->
	<!-- //Js files -->


</body>

</html>