backend_app/urls.py
from django.urls import path
from backend_app import views
from backend_app.apps import BackendAppConfig

app_name = BackendAppConfig.name

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about_us, name='about_us'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('add_to_cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('products/', views.products, name='products'),
    path('show_cart/', views.show_cart, name='show_cart'),
    path('forgot_password/', views.ForgotPassword.as_view(), name='forgot_password'),
    path('update_password/', views.UpdatePassword.as_view(), name='update_password'),
    path('update_product/<int:pk>/', views.update_product, name='update_product'),
    path('change_password/', views.ChangePassword.as_view(), name='change_password'),
    path('update_my_profile/', views.update_my_profile, name='update_my_profile'),
    path('add_product/', views.AddProduct.as_view(), name='add_product'),
    path('login/', views.MyLogin.as_view(), name='login'),
    path('register/', views.AdminRegistration.as_view(), name='admin_registration'),
    path('admin_index/', views.admin_index, name='admin_index'),
    path('view_products/', views.view_products, name='view_products'),
    path('add_category/', views.add_category, name='add_category'),
    path('view_categories/', views.view_categories, name='view_categories'),
    path('update_category/<int:pk>/', views.update_category, name='update_category'),
    path('qty_increase_decrease/', views.qty_increase_decrease, name='qty_increase_decrease'),
    path('checkout_page/', views.checkout_page, name='checkout_page'),
    path('delete_cart_item/<int:pk>/', views.delete_cart_item, name='delete_cart_item'),
    path('delete_category/<int:pk>/', views.delete_category, name='delete_category'),
    path('delete_product/<int:pk>/', views.delete_product, name='delete_product'),
]

creative_spaces/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from backend_app import views
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend_app.urls', namespace='backend')),
    path('professional/', include('professionals.urls', namespace='professionals')),
    path('user/', include('users.urls', namespace='users')),
    path('verify/', views.user_verification, name='verify'),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('forgot_password_verify/', views.forgot_password_verification, name='forgot_password_verification'),
    path('logout/', views.my_logout, name="logout"),
    path('payment_processing/', views.payment_processing, name='payment_processing'),
    path('payment_successful/', views.payment_successful, name='payment_successful'),
    path('payment_failed/', TemplateView.as_view(template_name='payment_failed'), name='payment_failed'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

professionals/urls.py
from django.urls import path
from professionals.apps import ProfessionalsConfig
from professionals import views


app_name = ProfessionalsConfig.name

urlpatterns =[
    path('registration/', views.ProfessionalRegistration.as_view(), name='professional_registration'),
    path('index/', views.professional_index, name='professional_index'),
    path('add_project/', views.AddProject.as_view(), name='add_project'),
    path('view_projects/', views.view_projects, name='view_projects'),
    path('answer_questions/', views.answer_questions, name='answer_questions'),
    path('update_project/<int:pk>/', views.update_project, name='update_project'),
    path('delete_project/<int:pk>/', views.delete_project, name='delete_project')
]

users/urls.py
from django.urls import path
from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path("register/", views.UserRegistration.as_view(), name="user_register"),
    path('index/', views.user_index, name='user_index'),
    path('ask_a_question/', views.ask_a_question, name='ask_a_question'),
    path('question/', views.question, name='question'),
    path('answer_questions/', views.answer_questions, name='answer_questions'),
    path('add_review/', views.add_review, name='add_review'),
    path('view_profile/', views.view_profile, name='view_profile'),
]

backend_app/forms.py
from django import forms
from backend_app.models import RoleDetails, Categories, ProductDetails, TemporaryCart, Sales, InvoiceTable


class RoleDetailForm(forms.ModelForm):
    class Meta:
        model = RoleDetails
        exclude = ['id', 'last_login', 'is_active', 'date_joined', 'first_name', 'last_name', 'username', 'email', 'mobile', 'password',
                   'role', 'address', 'verify_link', 'image', 'otp', 'otp_time', 'is_staff', 'is_superuser']


class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        exclude = ['c_id', 'c_name', 'image']


class ProductDetailForm(forms.ModelForm):
    class Meta:
        model = ProductDetails
        exclude = ['p_id', 'p_name', 'category', 'price', 'description', 'photo', 'cover_photo', 'quantity']


class TemporaryCartForm(forms.ModelForm):
    class Meta:
        model = TemporaryCart
        exclude = ['t_id', 'product', 'p_name', 'price', 'quantity', 'total_price', 'image']


class SalesForm(forms.ModelForm):
    class Meta:
        model = Sales
        exclude = ['t_id', 'u_email', 'product', 'p_name', 'price', 'quantity', 'total_price', 'image']


class InvoiceTableForm(forms.ModelForm):
    class Meta:
        model = InvoiceTable
        exclude = ['invoice', 'amount', 'u_email', 'status', 'token']

backend_app/views.py
from django.shortcuts import render, redirect, HttpResponse, Http404
from backend_app.models import RoleDetails, UserRole, Categories, ProductDetails, TemporaryCart, Sales, InvoiceTable
from professionals.models import Projects
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from misc_files.mailing import send_verify_link
from misc_files.generic_functions import generate_string
from django.views import View
from backend_app.forms import RoleDetailForm, CategoriesForm, ProductDetailForm, TemporaryCartForm, SalesForm, InvoiceTableForm
from django.contrib.auth.hashers import make_password, check_password
from django.core.files.storage import FileSystemStorage
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.views import login_required
from django.db.models import Sum
from paypal.standard.forms import PayPalPaymentsForm
from django.urls import reverse
from django.conf import settings


@method_decorator(csrf_exempt, name='dispatch')
class AdminRegistration(View):
    form = RoleDetailForm()

    def get(self, request):
        return render(request, 'registration.html')

    def post(self, request):
        self.form = RoleDetailForm(request.POST)
        if self.form.is_valid():
            if request.FILES:
                filename = request.FILES['image']
                fs = FileSystemStorage()
                my_file = fs.save(filename.name, filename)
                image = fs.url(my_file)
                image = filename.name
            f = self.form.save(commit=False)
            f.role_id = UserRole.objects.get(role_name='admin').role_id
            f.first_name = request.POST['first_name']
            f.last_name = request.POST['last_name']
            f.username = request.POST['first_name'] + "_" + request.POST['last_name']
            f.email = request.POST['email']
            f.image = image
            f.mobile = request.POST['mobile']
            f.password = make_password(request.POST['password'])
            f.address = request.POST['address']
            token = make_password(generate_string()).replace("+", "")
            verify_link = '127.0.0.1:8000/verify/?token={}'.format(token)
            f.verify_link = token
            f.is_staff = False
            f.is_superuser = False
            f.is_active = False
            f.save()
            try:
                send_verify_link(request.POST['email'], f.username, verify_link)
            except:
                print("!!!!!  Failed to send email  !!!!!")
            return redirect('/')
        else:
            return HttpResponse(status=400)


decorators = [login_required, csrf_exempt]


@method_decorator(decorators, name='dispatch')
class AddProduct(View):
    form = ProductDetailForm()

    def get(self, request):
        categories = Categories.objects.all()
        return render(request, 'add_product.html', {'categories': categories})

    def post(self, request):
        self.form = ProductDetailForm(request.POST)
        if self.form.is_valid():
            if request.FILES:
                filename1 = request.FILES['cover_photo']
                filename2 = request.FILES['photo']
                fs = FileSystemStorage()
                my_file1 = fs.save(filename1.name, filename1)
                my_file2 = fs.save(filename2.name, filename2)
                image1 = fs.url(my_file1)
                image2 = fs.url(my_file2)
                cover_photo = filename1.name
                photo = filename2.name
            f = self.form.save(commit=False)
            f.category_id = request.POST['cat']
            f.p_name = request.POST['p_name']
            f.price = request.POST['price']
            f.quantity = request.POST['quantity']
            f.description = request.POST['description']
            f.cover_photo = cover_photo
            f.photo = photo
            f.save()
        else:
            return HttpResponse(status=400)
        return redirect('/admin_index/')


def index(request):
    data = RoleDetails.objects.filter(role_id=UserRole.objects.get(role_name='admin').role_id).exists()
    categories = Categories.objects.all()
    products = ProductDetails.objects.all()
    professionals = RoleDetails.objects.filter(role__role_name='professional')[:3]
    products_dict = dict()
    for product in products:
        if product.category_id not in products_dict:
            products_dict.update({product.category_id: product})
    if data is True:
        request.session['admin_exists'] = True
    return render(request, 'index.html', {'categories': categories, 'products': products_dict.values(), 'professionals': professionals})


def about_us(request):
    return render(request, 'about_us.html')


def portfolio(request):
    projects = Projects.objects.all()
    return render(request, 'portfolio.html', {'projects': projects})


@method_decorator(csrf_exempt, name='dispatch')
class MyLogin(View):
    def get(self, request, message=None):
        if message is None:
            if request.session.get('_auth_user_id') is None:
                return render(request, 'login.html')
            else:
                role = RoleDetails.objects.get(pk=request.session.get('_auth_user_id')).role.role_name
                if role == 'admin':
                    return redirect('/admin_index/')
                elif role == 'professional':
                    return redirect('/professional/index/')
                elif role == 'user':
                    return redirect('/user/index/')
        else:
            return render(request, 'login.html', {message: True})

    def post(self, request):
        try:
            detail = RoleDetails.objects.get(email=request.POST['email'])
        except:
            return self.get(request, 'email_invalid')
        else:
            if check_password(request.POST['password'], detail.password):
                if detail.is_active is True:
                    user = authenticate(request, username=detail.username, password=request.POST['password'])
                    if user is not None:
                        login(request, user)
                        request.session['image'] = detail.image
                        request.session['role'] = detail.role.role_name
                        request.session['logged_in'] = True
                        if detail.role.role_name == 'admin':
                            return redirect('/admin_index/')
                        elif detail.role.role_name == 'user':
                            return redirect('/user/index/')
                        elif detail.role.role_name == 'professional':
                            return redirect('/professional/index/')
                else:
                    return self.get(request, 'not_verify')
            else:
                return self.get(request, 'password_invalid')


@method_decorator(decorators, name='dispatch')
class UpdatePassword(View):
    def get(self, request, message=None):
        if message is None:
            return render(request, 'update_password.html')
        else:
            return render(request, 'update_password.html', {message: True})

    def post(self, request):
        detail = RoleDetails.objects.get(pk=request.session.get('_auth_user_id'))
        if check_password(request.POST['old_password'], detail.password):
            if request.POST['new_password'] == request.POST['confirm_password']:
                password = make_password(request.POST['new_password'])
                update = RoleDetails(id=detail.id, password=password)
                update.save(update_fields=['password'])

                role = RoleDetails.objects.get(pk=request.session.get('_auth_user_id')).role.role_name
                if role == 'admin':
                    return redirect('/admin_index/')
                elif role == 'professional':
                    return redirect('/professional/index/')
                elif role == 'user':
                    return redirect('/user/index/')
            else:
                return self.get(request, 'passwords_donot_match')
        else:
            return self.get(request, 'invalid_password')


@csrf_exempt
@login_required
def add_category(request):
    if request.method == "POST":
        image = request.session['image']
        form = CategoriesForm(request.POST)
        if form.is_valid():
            if request.FILES:
                filename = request.FILES['image']
                fs = FileSystemStorage()
                my_file = fs.save(filename.name, filename)
                image = fs.url(my_file)
                image = filename.name
            f = form.save(commit=False)
            f.c_name = request.POST['category_add']
            f.image = image
            f.save()
            return redirect('/view_categories/')
    return render(request, 'add_category.html')


@login_required
def admin_index(request):
    return render(request, 'admin_index.html')


@login_required
def view_categories(request):
    category = Categories.objects.all()
    return render(request, 'view_categories.html', {'categories': category})


@csrf_exempt
@login_required
def update_category(request, pk):
    data = Categories.objects.get(pk=pk)
    if request.method == 'POST':
        image = data.image
        if request.FILES:
            filename = request.FILES['image']
            fs = FileSystemStorage()
            my_file = fs.save(filename.name, filename)
            image = fs.url(my_file)
            image = filename.name
        name = request.POST['cattt']
        update = Categories(c_id=data.c_id, c_name=name, image=image)
        update.save(update_fields=['c_name', 'image'])
        return redirect('/view_categories/')
    return render(request, 'update_category.html', {'data': data})


@login_required
def my_logout(request):
    logout(request)
    request.session.flush()
    return redirect('/')


@method_decorator(csrf_exempt, name='dispatch')

backend_app/templates/admin_master.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{% block title %}{% endblock %}</title>

  <!-- Template CSS -->
  <link rel="stylesheet" href="/static/admin_panel/css/style-starter.css">
  {% block style %}
  {% endblock %}

  <!-- google fonts -->
  <link href="//fonts.googleapis.com/css?family=Nunito:300,400,600,700,800,900&display=swap" rel="stylesheet">
</head>


<body class="sidebar-menu-collapsed">
  <div class="se-pre-con"></div>
<section>
  <!-- sidebar menu start -->
  <div class="sidebar-menu sticky-sidebar-menu">

    <!-- logo start -->
    <div class="logo">
      <h1><a href="#">Dashboard</a></h1>
    </div>

  <!-- if logo is image enable this -->
    <!-- image logo --
    <div class="logo">
      <a href="index.html">
        <img src="image-path" alt="Your logo" title="Your logo" class="img-fluid" style="height:35px;" />
      </a>
    </div>
     //image logo -->

    <div class="logo-icon text-center">
      <a href="/" title="dashboard"><img src="/static/admin_panel/images/logo.png" alt="dashboard-icon"> </a>
    </div>
    <!-- //logo end -->

    <div class="sidebar-menu-inner">

      <!-- sidebar nav start -->
      <ul class="nav nav-pills nav-stacked custom-nav">
        {% if request.session.role == 'admin' %}
        <li class="active"><a href="{% url 'backend:admin_index' %}"><i class="fa fa-tachometer"></i><span> Dashboard</span></a>
        </li>
        {% elif request.session.role == 'professional' %}
        <li class="active"><a href="{% url 'professionals:professional_index' %}"><i class="fa fa-tachometer"></i><span> Dashboard</span></a>
        </li>
        {% elif request.session.role == 'user' %}
        <li class="active"><a href="{% url 'users:user_index' %}"><i class="fa fa-tachometer"></i><span> Dashboard</span></a>
        </li>
        {% endif %}


        {% if request.session.role == "admin" %}

          <li class="menu-list">
          <a href="#"><i class="fa fa-th"></i>
            <span>Manage Categories <i class="lnr lnr-chevron-right"></i></span></a>
          <ul class="sub-menu-list">
            <li><a href="{% url 'backend:add_category' %}">Add category</a> </li>
            <li><a href="{% url 'backend:view_categories' %}">View categories</a> </li>
          </ul>
        </li>
          <li class="menu-list">
          <a href="#"><i class="fa fa-table"></i>
            <span>Manage Products <i class="lnr lnr-chevron-right"></i></span></a>
          <ul class="sub-menu-list">
              <li><a href="/add_product/">Add product</a> </li>
            <li><a href="/view_products/">View products</a> </li>
          </ul>
        </li>
        {% endif %}

        {% if request.session.role == "professional" %}
          <li class="menu-list">
          <a href="#"><i class="fa fa-image"></i>
            <span>Manage Projects <i class="lnr lnr-chevron-right"></i></span></a>
          <ul class="sub-menu-list">
              <li><a href="{% url 'professionals:add_project' %}">Add Project</a> </li>
            <li><a href="{% url 'professionals:view_projects' %}">View Projects</a> </li>
          </ul>
        </li>

        <li><a href="/professional/answer_questions/"><i class="fa fa-th"></i> <span>Questions</span></a></li>
        {% endif %}

        {% if request.session.role == "user" %}
        <li><a href="/user/answer_questions/"><i class="fa fa-th"></i> <span>Answers from Professional</span></a></li>
        {% endif %}
        <li><a href="/update_my_profile/"><i class="fa fa-user"></i> <span>Update Profile</span></a></li>
        <li><a href="/logout/"><i class="fa fa-power-off"></i> <span>Log Out</span></a></li>
        <!--<li><a href="blocks.html"><i class="fa fa-th"></i> <span>Content blocks</span></a></li>
        <li><a href="forms.html"><i class="fa fa-file-text"></i> <span>Forms</span></a></li>-->
      </ul>
      <!-- //sidebar nav end -->
      <!-- toggle button start -->
      <a class="toggle-btn">
        <i class="fa fa-angle-double-left menu-collapsed__left"><span>Collapse Sidebar</span></i>
        <i class="fa fa-angle-double-right menu-collapsed__right"></i>
      </a>
      <!-- //toggle button end -->
    </div>
  </div>
  <!-- //sidebar menu end -->
  <!-- header-starts -->
  <div class="header sticky-header">

    <!-- notification menu start -->
    <div class="menu-right">
      <div class="navbar user-panel-top">
        <div class="user-dropdown-details d-flex">
          <div class="profile_details">
            <ul>
              <li class="dropdown profile_details_drop">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdownMenu3" aria-haspopup="true"
                  aria-expanded="false">
                  <div class="profile_img">
                    <img src="/media/{{ request.session.image }}" class="rounded-circle" alt="" />
                    <div class="user-active">
                      <span></span>
                    </div>
                  </div>
                </a>
                <ul class="dropdown-menu drp-mnu" aria-labelledby="dropdownMenu3">
                  <li class="user-info">
                    <h5 class="user-name">{{ request.user.get_full_name }}</h5>
                  </li>
                  <li> <a href="#"><i class="lnr lnr-user"></i>My Profile</a> </li>
                  <li> <a href="{% url 'backend:update_password' %}"><i class="lnr lnr-cog"></i>Change Password</a> </li>
                  <li class="logout"> <a href="/logout/"><i class="fa fa-power-off"></i> Logout</a> </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!--notification menu end -->
  </div>
  <!-- //header-ends -->





    {% block content %}{% endblock %}






</section>

<!-- move top -->
<button onclick="topFunction()" id="movetop" class="bg-primary" title="Go to top">
  <span class="fa fa-angle-up"></span>
</button>
<script>
  // When the user scrolls down 20px from the top of the document, show the button
  window.onscroll = function () {
    scrollFunction()
  };

  function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
      document.getElementById("movetop").style.display = "block";
    } else {
      document.getElementById("movetop").style.display = "none";
    }
  }

  // When the user clicks on the button, scroll to the top of the document
  function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
  }
</script>
<!-- /move top -->


<script src="/static/admin_panel/js/jquery-3.3.1.min.js"></script>
<script src="/static/admin_panel/js/jquery-1.10.2.min.js"></script>

<!-- chart js -->
<script src="/static/admin_panel/js/Chart.min.js"></script>
<script src="/static/admin_panel/js/utils.js"></script>
<!-- //chart js -->

<!-- Different scripts of charts.  Ex.Barchart, Linechart -->
<script src="/static/admin_panel/js/bar.js"></script>
<script src="/static/admin_panel/js/linechart.js"></script>
<!-- //Different scripts of charts.  Ex.Barchart, Linechart -->


<script src="/static/admin_panel/js/jquery.nicescroll.js"></script>
<script src="/static/admin_panel/js/scripts.js"></script>

<!-- close script -->
<script>
  var closebtns = document.getElementsByClassName("close-grid");
  var i;

  for (i = 0; i < closebtns.length; i++) {
    closebtns[i].addEventListener("click", function () {
      this.parentElement.style.display = 'none';
    });
  }
</script>
<!-- //close script -->

<!-- disable body scroll when navbar is in active -->
<script>
  $(function () {
    $('.sidebar-menu-collapsed').click(function () {
      $('body').toggleClass('noscroll');
    })
  });
</script>
<!-- disable body scroll when navbar is in active -->

 <!-- loading-gif Js -->
 <script src="/static/admin_panel/js/modernizr.js"></script>
 <script>
     $(window).load(function () {
         // Animate loader off screen
         $(".se-pre-con").fadeOut("slow");;
     });
 </script>
 <!--// loading-gif Js -->

<!-- Bootstrap Core JavaScript -->
<script src="/static/admin_panel/js/bootstrap.min.js"></script>

<!-- disable back button on page -->

</body>

</html>